development:
  GITHUB_KEY: 4bac6bd81cf0ac863530
  GITHUB_SECRET: 97ebbed3a75d5d0985ad660d503641205737064d
  CONSUMER_KEY: LaQPaifxeUl8W2CL84k7je4zv
  CONSUMER_SECRET: QGkNPYIgzsp9mnSOjhz9KuRI9FsKHdrVyQ0w2PBgeWMInTOkex
production:
  GITHUB_KEY: 07d00f4549442f49e5bb
  GITHUB_SECRET: f80813e2ab379ac9ce32a3d5b5cfc4bea1e7b122
  CONSUMER_KEY: LaQPaifxeUl8W2CL84k7je4zv
  CONSUMER_SECRET: QGkNPYIgzsp9mnSOjhz9KuRI9FsKHdrVyQ0w2PBgeWMInTOkex
