default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/sp_development

test:
  <<: *default
  database: db/sp_test

production:
  <<: *default
  database: db/sp_production
