default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/ziita_development

test:
  <<: *default
  database: db/ziita_test

production:
  <<: *default
  database: db/ziita_production
